### ISSUE TITLE
Is there anything else I need for this to work?

### ISSUE THREAD

**Issue by arlair** [CyclicMaterials/molecule-input#129]
Hi,

I had some trouble using the master branch as I am using the latest Cycle.js.

I tried to npm install from a branch, but I was getting issues finding the modules. This might have been a WebPack issue, I'm not sure.

I was using this boilerplate:
https://github.com/Cmdv/cycle-webpack-boilerplate

I ended up getting started by cloning this repo and using the develop branch and npm link. I had to add some config to get WebPack to find the other Cyclic modules, but it runs now.

It looks nearly correct, but some things are not working, like the colour when you focus or the labels floating do not float when you type in them.

I used the ES6 code on the main page to create an input:

```
import {Input} from '@cyclic/molecule-input';

Input({
  DOM, props$: Observable.just({
    label: `total`, type: `number`, prefix: `$`, className: `short`,
  }),
}).DOM,
```

Then I included the following CSS:

```
require("!style!css!../node_modules/@cyclic/molecule-input/lib/index.css");
```

Do you know if there is anything else I would be needing?

Thanks.

**Comment by Frikki** [comment]
No, that ought to work. With all the changes that has happened with Cycle.js, these libraries are in need of updates. Also, I am looking into using Free-Style for CSS.

If you inspect the HTML output in the browser, do you see CSS classes added and removed on focus/blur?

**Comment by arlair** [comment]
Clicking on and off the input I don't notice any CSS class changes in Chrome Dev Tools.
