### ISSUE TITLE
Numeric fields allow`e` and `.`, which provokes weird label behavior. 

### ISSUE THREAD

**Issue by kirjs** [CyclicMaterials/molecule-input#25]
Looks like the former is know behavior in Chrome. But the label probably should still jump up. 

<img width="242" alt="screen shot 2015-09-20 at 3 43 46 pm" src="https://cloud.githubusercontent.com/assets/2545357/9982566/9d812ddc-5fae-11e5-9a35-a45cb9ce9183.png">

This is for example before the last one in the demo

**Comment by Frikki** [comment]
Yes. The behavior should be that the label floats.
