### ISSUE TITLE
Shorten the require path

### ISSUE THREAD

**Issue by kirjs** [CyclicMaterials/molecule-input#26]
Currently I have to do something like this to require the module:
`import moleculeInput from '@cyclic/molecule-input/src/molecule-input`.

**Comment by Frikki** [comment]
Yes? How would you like it to be, @kirjs?

**Comment by Frikki** [comment]
@kirjs 
The package contains several components:
- molecule-input-char-counter,
- molecule-input-container,
- molecule-input-error,
- molecule-input, and
- molecule-textarea

A component can be required either transpiled to ES 5 or as ES 6, e.g.:
- Transpiled to ES 5 from _/lib_
  
  ``` js
  import moleculeInput from '@cyclic/molecule-input/lib/molecule-input'
  ```
  
  or
- ES 6 from _/src_
  
  ``` js
  import moleculeInput from '@cyclic/molecule-input/src/molecule-input'
  ```

It would, of course, be possible to make _/src_ default and provide named imports with a "shortcut".

For example:

``` js
import {moleculeImport} from '@cyclic/molecule-input'
```

I think that would make it easier to use. What do you think?

**Comment by kirjs** [comment]
Do you have react installed?

**Comment by Frikki** [comment]
@kirjs No, but I have worked with react. They use a main file which imports the different modules and re-exports them in an object (as far as I remember).

I will do the same for all Cyclic Materials components. The main file will point to _./lib/index.js_. The _./lib_ directory holds all components transpiled to ES 5. That way,requiring components will default to the transpiled components. If a consumers want to transpile the components with their own source code, they can import from _./src_.

### CommonJS

**Require a specific component:**

``` js
var moleculeInput = require('@cyclic/molecule-input').moleculeInput;
```

**Require all components:**

``` js
var cyclicMoleculeInput = require('@cyclic/molecule-input');

// The components are now accessible as properties, e.g.:
var myInstance = cyclicMoleculeInput.moleculeInput({DOM, props$});
```

### The ES 6  Way

**Import a specific component:**

``` js
import {moleculeInput} from '@cyclic/molecule-input'
```

**Import all components:**

``` js
import * as cyclicMoleculeInput from '@cyclic/molecule-input'

// The components are now accessible as properties, e.g.:
const myInstance = cyclicMoleculeInput.moleculeInput({DOM, props$});
```

**Import a specific component from source:**

``` js
import moleculeInput from '@cyclic/molecule-input/src/molecule-input'
```

What do you think?

**Comment by kirjs** [comment]
Sorry, my previous comment was meant for a completely different GH issue, not sure how it got here.

The proposal above is a great improvement over the current API, and it resolves the issue above. 

My only small concern is that `moleculeInput` in this case means 2 things: 
- It's name of the package
- It's also name of a component of the package. 

This makes it a bit confusing, and causes questions, e.g. why is `textarea`  part of  `input`, while generally users  are used for them to be on the same level semantically (e.g. in html) 

It's minor, but worth thinking about.

**Comment by Frikki** [comment]
@kirjs Yes, it can be confusing. I think that the components within the package should lose the _molecule_ prefix.

_Textarea_ is part of the package because it is an input component that internally uses other _molecule-input_ components.

**Update**

I am also considering renaming the component functions to `makeComponentName()` or `createComponentName()`. It is more in line with what they actually do.

**Update**

After a talk with @staltz, components will be capitalized, e.g., `InputContainer()`.
