### ISSUE TITLE
Document adding CSS

### ISSUE THREAD

**Issue by kirjs** [CyclicMaterials/molecule-input#27]
I couldn't find a good way to do that

**Comment by Frikki** [comment]
Do you mean importing the component CSS files into your own project?

**Comment by kirjs** [comment]
Yes, I had a hard time trying to importing the styles and making the components look right.

**Comment by Frikki** [comment]
This will be more obvious with the new structure in the next major release v6.0.0, just around the corner.

**Comment by Frikki** [comment]
@kirjs Check updated [README](https://github.com/CyclicMaterials/molecule-input/blob/master/README.md)

Closed by https://github.com/CyclicMaterials/molecule-input/commit/2d1dd3cfa029af66932ceaf1904c679ad523a026
