### ISSUE TITLE
Suggestion: Character counter with minimum amount of characters

### ISSUE THREAD

**Issue by TylorS** [CyclicMaterials/molecule-input#28]
I think it would be useful to have an option to specify an minimum amount of characters needed for a input. It's often found that in an attempt to have user's create more secure passwords, you might say that their password must be at least `n` number of characters long to avoid short more insecure passwords.

**Comment by Frikki** [comment]
@TylorS The character counter is just a counter. It doesn’t and shouldn’t validate patterns. Setting an INPUT’s `pattern` attribute affect the validation.

For example: `<input pattern="^[a-zA-Z][a-zA-Z0-9_]{3,14}$" type="password">`

The password's first character must be a letter, it must contain at least 4 characters and no more than 15 characters and no characters other than letters, numbers and the underscore may be used.

**Matches:** `abcd | aBc45DSD_sdf | password`
**Non-Matches:** `afv | 1234 | reallylongpassword`

Setting it up with a character counter and bells and whistles:

``` js
moleculeInput({
  DOM, props$: Rx.Observable.just({
    label: `password only letters, numbers and underscore`,
    type: `password`,
    required: true,
    pattern: `^[a-zA-Z][a-zA-Z0-9_]{3,14}$`,
    autoValidate: true,
    maxLength: 15,
    charCounter: true,
    errorMessage: `Must start with a letter. Min. 4 chars. Max. 15 chars.`,
  }),
})
```

I will add this as an example to the demo.

See [common validation patterns](http://html5pattern.com/).

**Comment by TylorS** [comment]
Awesome, I really haven't used this yet (apologies). Was just going by your demo.
Really great to see how robust you've made this though!
